apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: gitops
  namespace: gitops
  labels:
    app.kubernetes.io/instance: gitops
spec:
  server:
    autoscale:
      enabled: false
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    insecure: false
    route:
      annotations: {}
      enabled: true
      path: /
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: reencrypt
      wildcardPolicy: None
    service:
      type: ""
  rbac:
    defaultPolicy: 'role:admin'
  resourceCustomizations: |
    route.openshift.io/Route:
      ignoreDifferences: |
        jsonPointers:
        - /spec/host
    image.openshift.io/ImageStream:
      ignoreDifferences: |
        jqPathExpressions:
        - .spec.tags[]?.generation
        - .spec.tags[]?.annotations
  resourceExclusions: |
    - apiGroups:
      - tekton.dev
      clusters:
      - '*'
      kinds:
      - PipelineRun
      - TaskRun
